export const siteConfig = {
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://codexpet.top",
  title: "Awesome Codex Pet",
  altNames: [
    "Codex Pet Gallery",
    "Codex 宠物画廊",
    "Codex 精品宠物",
    "Codex 小宠物",
    "Codex Pets Community",
    "Codex Pet Store",
    "Codex 宠物商店",
  ],
  description:
    "Browse a free community gallery of OpenAI Codex pets, preview every animation, and install anime, game, mascot, animal, and original companions in one step. Request a character for the community to make.",
  descriptionZh:
    "Awesome Codex Pet 是免费的社区 Codex 小宠物画廊，像宠物商店一样提供动漫、游戏、吉祥物、动物和原创伙伴的完整预览与一键安装，也可免费提交喜欢角色的社区制作申请。",
  shortDescription:
    "A free community Codex pet gallery with full previews, one-step installation, and character requests.",
  shortDescriptionZh:
    "免费的 Codex 小宠物社区画廊，提供完整预览、一键安装与角色制作申请。",
  ogImage: "/assets/cover/awesome-codex-pet-cover.png",
  ogImageWidth: 1659,
  ogImageHeight: 948,
  repo: "https://github.com/legeling/awesome-codex-pet",
  catalog: "/pets.json",
  collectionsCatalog: "/collections.json",
  requestsCatalog: "/requests.json",
  keywords: [
    "Codex",
    "Codex pet",
    "Codex pets",
    "custom Codex pet",
    "Codex custom pets",
    "install Codex pet",
    "how to install Codex pet",
    "Codex pet gallery",
    "Codex pets gallery",
    "Codex pets library",
    "Codex pet store",
    "free Codex pets",
    "Codex pet download",
    "download Codex pet",
    "request Codex pet",
    "free Codex pet request",
    "community Codex pet request",
    "Codex pet share",
    "Codex pet skill",
    "Codex Hatch Pet",
    "Hatch Pet skill",
    "create Codex pet",
    "Codex pet not showing",
    "Codex /pet not working",
    "Codex pet V1",
    "Codex pet V2",
    "Codex desktop companion",
    "Codex CLI",
    "OpenAI Codex",
    "desktop pet",
    "pixel art pet",
    "anime Codex pet",
    "game character Codex pet",
    "spritesheet",
    "Codex 宠物",
    "Codex 小宠物",
    "Codex 精品宠物",
    "Codex 宠物网站",
    "Codex 宠物社区",
    "Codex 宠物市场",
    "Codex 小宠物商店",
    "免费 Codex 宠物",
    "Codex 宠物下载",
    "Codex 宠物安装",
    "Codex 宠物制作申请",
    "免费申请 Codex 小宠物",
    "请社区制作 Codex 宠物",
    "Codex 宠物制作",
    "Codex 宠物自定义",
    "Codex 小宠物制作",
    "Codex 宠物不显示",
    "Codex 宠物有什么用",
    "Codex 宠物功能",
    "Codex 宠物 skill",
    "ChatGPT 桌面宠物",
    "动漫桌面宠物",
    "代码助手宠物",
    "open source pet",
    "Awesome Codex Pet",
  ],
};

export type SiteConfig = typeof siteConfig;
